apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: rehs-2026-chatbot
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pod-reader
  namespace: rehs-2026-chatbot
subjects:
  - kind: ServiceAccount
    name: default
    namespace: rehs-2026-chatbot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
